version: "3.6"

services:
  app:
    build: ./
    container_name: staging-athletex-api-app
    volumes:
      - ./:/athletex-dao-api
    ports:
      - "8081:8081"
    expose:
      - 8081
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

