package io.athletex.client.apis.stats


val sampleMlbStatsJson = "[\n" +
        "    {\n" +
        "        \"StatID\": 3643733,\n" +
        "        \"TeamID\": 17,\n" +
        "        \"PlayerID\": 10000005,\n" +
        "        \"SeasonType\": 1,\n" +
        "        \"Season\": 2022,\n" +
        "        \"Name\": \"Andrew Chafin\",\n" +
        "        \"Team\": \"DET\",\n" +
        "        \"Position\": \"RP\",\n" +
        "        \"PositionCategory\": \"P\",\n" +
        "        \"Started\": 0,\n" +
        "        \"BattingOrder\": null,\n" +
        "        \"GlobalTeamID\": 10000017,\n" +
        "        \"AverageDraftPosition\": null,\n" +
        "        \"AuctionValue\": null,\n" +
        "        \"Updated\": \"2022-07-17T12:50:30\",\n" +
        "        \"Games\": 33,\n" +
        "        \"FantasyPoints\": 23.33,\n" +
        "        \"AtBats\": 0.00,\n" +
        "        \"Runs\": 0.00,\n" +
        "        \"Hits\": 0.00,\n" +
        "        \"Singles\": 0.00,\n" +
        "        \"Doubles\": 0.00,\n" +
        "        \"Triples\": 0.00,\n" +
        "        \"HomeRuns\": 0.00,\n" +
        "        \"RunsBattedIn\": 0.00,\n" +
        "        \"BattingAverage\": 0,\n" +
        "        \"Outs\": 0.00,\n" +
        "        \"Strikeouts\": 0.00,\n" +
        "        \"Walks\": 0.00,\n" +
        "        \"HitByPitch\": 0.00,\n" +
        "        \"Sacrifices\": 0.00,\n" +
        "        \"SacrificeFlies\": 0.00,\n" +
        "        \"GroundIntoDoublePlay\": 0.00,\n" +
        "        \"StolenBases\": 0.00,\n" +
        "        \"CaughtStealing\": 0.00,\n" +
        "        \"PitchesSeen\": 0.00,\n" +
        "        \"OnBasePercentage\": 0,\n" +
        "        \"SluggingPercentage\": 0,\n" +
        "        \"OnBasePlusSlugging\": 0,\n" +
        "        \"Errors\": 1.00,\n" +
        "        \"Wins\": 0.00,\n" +
        "        \"Losses\": 1.00,\n" +
        "        \"Saves\": 1.00,\n" +
        "        \"InningsPitchedDecimal\": 28.3333333333,\n" +
        "        \"TotalOutsPitched\": 85.00,\n" +
        "        \"InningsPitchedFull\": 28.00,\n" +
        "        \"InningsPitchedOuts\": 1.00,\n" +
        "        \"EarnedRunAverage\": 2.224,\n" +
        "        \"PitchingHits\": 18.00,\n" +
        "        \"PitchingRuns\": 8.00,\n" +
        "        \"PitchingEarnedRuns\": 7.00,\n" +
        "        \"PitchingWalks\": 9.00,\n" +
        "        \"PitchingStrikeouts\": 34.00,\n" +
        "        \"PitchingHomeRuns\": 1.00,\n" +
        "        \"PitchesThrown\": 437.00,\n" +
        "        \"PitchesThrownStrikes\": 281.00,\n" +
        "        \"WalksHitsPerInningsPitched\": 0.953,\n" +
        "        \"PitchingBattingAverageAgainst\": 0.178,\n" +
        "        \"GrandSlams\": 0.00,\n" +
        "        \"FantasyPointsFanDuel\": 166.00,\n" +
        "        \"FantasyPointsDraftKings\": 100.35,\n" +
        "        \"FantasyPointsYahoo\": 28.90,\n" +
        "        \"PlateAppearances\": 0.00,\n" +
        "        \"TotalBases\": 0.00,\n" +
        "        \"FlyOuts\": 0.00,\n" +
        "        \"GroundOuts\": 0.00,\n" +
        "        \"LineOuts\": 0.00,\n" +
        "        \"PopOuts\": 0.00,\n" +
        "        \"IntentionalWalks\": 0.00,\n" +
        "        \"ReachedOnError\": 0.00,\n" +
        "        \"BallsInPlay\": 0.00,\n" +
        "        \"BattingAverageOnBallsInPlay\": 0,\n" +
        "        \"WeightedOnBasePercentage\": 0,\n" +
        "        \"PitchingSingles\": 14.00,\n" +
        "        \"PitchingDoubles\": 3.00,\n" +
        "        \"PitchingTriples\": 0.00,\n" +
        "        \"PitchingGrandSlams\": 0.00,\n" +
        "        \"PitchingHitByPitch\": 2.00,\n" +
        "        \"PitchingSacrifices\": 1.00,\n" +
        "        \"PitchingSacrificeFlies\": 1.00,\n" +
        "        \"PitchingGroundIntoDoublePlay\": 3.00,\n" +
        "        \"PitchingCompleteGames\": 0.00,\n" +
        "        \"PitchingShutOuts\": 0.00,\n" +
        "        \"PitchingNoHitters\": 0.00,\n" +
        "        \"PitchingPerfectGames\": 0.00,\n" +
        "        \"PitchingPlateAppearances\": 114.00,\n" +
        "        \"PitchingTotalBases\": 24.00,\n" +
        "        \"PitchingFlyOuts\": 10.00,\n" +
        "        \"PitchingGroundOuts\": 15.00,\n" +
        "        \"PitchingLineOuts\": 3.00,\n" +
        "        \"PitchingPopOuts\": 7.00,\n" +
        "        \"PitchingIntentionalWalks\": 0.00,\n" +
        "        \"PitchingReachedOnError\": 4.00,\n" +
        "        \"PitchingCatchersInterference\": 0.00,\n" +
        "        \"PitchingBallsInPlay\": 67.00,\n" +
        "        \"PitchingOnBasePercentage\": 0.254,\n" +
        "        \"PitchingSluggingPercentage\": 0.238,\n" +
        "        \"PitchingOnBasePlusSlugging\": 0.492,\n" +
        "        \"PitchingStrikeoutsPerNineInnings\": 10.80,\n" +
        "        \"PitchingWalksPerNineInnings\": 2.86,\n" +
        "        \"PitchingBattingAverageOnBallsInPlay\": 0.254,\n" +
        "        \"PitchingWeightedOnBasePercentage\": 0.263,\n" +
        "        \"DoublePlays\": 0.00,\n" +
        "        \"PitchingDoublePlays\": 3.00,\n" +
        "        \"BattingOrderConfirmed\": true,\n" +
        "        \"IsolatedPower\": 0,\n" +
        "        \"FieldingIndependentPitching\": 2.33,\n" +
        "        \"PitchingQualityStarts\": 0.00,\n" +
        "        \"PitchingInningStarted\": null,\n" +
        "        \"LeftOnBase\": 0.00,\n" +
        "        \"PitchingHolds\": 12.00,\n" +
        "        \"PitchingBlownSaves\": 0.00,\n" +
        "        \"SubstituteBattingOrder\": null,\n" +
        "        \"SubstituteBattingOrderSequence\": null,\n" +
        "        \"FantasyPointsFantasyDraft\": 100.35,\n" +
        "        \"FantasyPointsBatting\": 0.00,\n" +
        "        \"FantasyPointsPitching\": 23.33\n" +
        "    },\n" +
        "    {\n" +
        "        \"StatID\": 3602948,\n" +
        "        \"TeamID\": 35,\n" +
        "        \"PlayerID\": 10000007,\n" +
        "        \"SeasonType\": 1,\n" +
        "        \"Season\": 2022,\n" +
        "        \"Name\": \"Patrick Corbin\",\n" +
        "        \"Team\": \"WSH\",\n" +
        "        \"Position\": \"SP\",\n" +
        "        \"PositionCategory\": \"P\",\n" +
        "        \"Started\": 19,\n" +
        "        \"BattingOrder\": null,\n" +
        "        \"GlobalTeamID\": 10000035,\n" +
        "        \"AverageDraftPosition\": null,\n" +
        "        \"AuctionValue\": null,\n" +
        "        \"Updated\": \"2022-07-17T12:50:30\",\n" +
        "        \"Games\": 19,\n" +
        "        \"FantasyPoints\": 50.66,\n" +
        "        \"AtBats\": 0.00,\n" +
        "        \"Runs\": 0.00,\n" +
        "        \"Hits\": 0.00,\n" +
        "        \"Singles\": 0.00,\n" +
        "        \"Doubles\": 0.00,\n" +
        "        \"Triples\": 0.00,\n" +
        "        \"HomeRuns\": 0.00,\n" +
        "        \"RunsBattedIn\": 0.00,\n" +
        "        \"BattingAverage\": 0,\n" +
        "        \"Outs\": 0.00,\n" +
        "        \"Strikeouts\": 0.00,\n" +
        "        \"Walks\": 0.00,\n" +
        "        \"HitByPitch\": 0.00,\n" +
        "        \"Sacrifices\": 0.00,\n" +
        "        \"SacrificeFlies\": 0.00,\n" +
        "        \"GroundIntoDoublePlay\": 0.00,\n" +
        "        \"StolenBases\": 0.00,\n" +
        "        \"CaughtStealing\": 0.00,\n" +
        "        \"PitchesSeen\": 0.00,\n" +
        "        \"OnBasePercentage\": 0,\n" +
        "        \"SluggingPercentage\": 0,\n" +
        "        \"OnBasePlusSlugging\": 0,\n" +
        "        \"Errors\": 0.00,\n" +
        "        \"Wins\": 4.00,\n" +
        "        \"Losses\": 12.00,\n" +
        "        \"Saves\": 0.00,\n" +
        "        \"InningsPitchedDecimal\": 99.6666666667,\n" +
        "        \"TotalOutsPitched\": 299.00,\n" +
        "        \"InningsPitchedFull\": 99.00,\n" +
        "        \"InningsPitchedOuts\": 2.00,\n" +
        "        \"EarnedRunAverage\": 5.870,\n" +
        "        \"PitchingHits\": 134.00,\n" +
        "        \"PitchingRuns\": 76.00,\n" +
        "        \"PitchingEarnedRuns\": 65.00,\n" +
        "        \"PitchingWalks\": 35.00,\n" +
        "        \"PitchingStrikeouts\": 91.00,\n" +
        "        \"PitchingHomeRuns\": 17.00,\n" +
        "        \"PitchesThrown\": 1711.00,\n" +
        "        \"PitchesThrownStrikes\": 1100.00,\n" +
        "        \"WalksHitsPerInningsPitched\": 1.696,\n" +
        "        \"PitchingBattingAverageAgainst\": 0.313,\n" +
        "        \"GrandSlams\": 0.00,\n" +
        "        \"FantasyPointsFanDuel\": 425.00,\n" +
        "        \"FantasyPointsDraftKings\": 191.55,\n" +
        "        \"FantasyPointsYahoo\": -84.80,\n" +
        "        \"PlateAppearances\": 0.00,\n" +
        "        \"TotalBases\": 0.00,\n" +
        "        \"FlyOuts\": 0.00,\n" +
        "        \"GroundOuts\": 0.00,\n" +
        "        \"LineOuts\": 0.00,\n" +
        "        \"PopOuts\": 0.00,\n" +
        "        \"IntentionalWalks\": 0.00,\n" +
        "        \"ReachedOnError\": 0.00,\n" +
        "        \"BallsInPlay\": 0.00,\n" +
        "        \"BattingAverageOnBallsInPlay\": 0,\n" +
        "        \"WeightedOnBasePercentage\": 0,\n" +
        "        \"PitchingSingles\": 91.00,\n" +
        "        \"PitchingDoubles\": 23.00,\n" +
        "        \"PitchingTriples\": 3.00,\n" +
        "        \"PitchingGrandSlams\": 0.00,\n" +
        "        \"PitchingHitByPitch\": 3.00,\n" +
        "        \"PitchingSacrifices\": 1.00,\n" +
        "        \"PitchingSacrificeFlies\": 1.00,\n" +
        "        \"PitchingGroundIntoDoublePlay\": 8.00,\n" +
        "        \"PitchingCompleteGames\": 1.00,\n" +
        "        \"PitchingShutOuts\": 0.00,\n" +
        "        \"PitchingNoHitters\": 0.00,\n" +
        "        \"PitchingPerfectGames\": 0.00,\n" +
        "        \"PitchingPlateAppearances\": 468.00,\n" +
        "        \"PitchingTotalBases\": 214.00,\n" +
        "        \"PitchingFlyOuts\": 48.00,\n" +
        "        \"PitchingGroundOuts\": 81.00,\n" +
        "        \"PitchingLineOuts\": 27.00,\n" +
        "        \"PitchingPopOuts\": 14.00,\n" +
        "        \"PitchingIntentionalWalks\": 1.00,\n" +
        "        \"PitchingReachedOnError\": 11.00,\n" +
        "        \"PitchingCatchersInterference\": 0.00,\n" +
        "        \"PitchingBallsInPlay\": 321.00,\n" +
        "        \"PitchingOnBasePercentage\": 0.368,\n" +
        "        \"PitchingSluggingPercentage\": 0.5,\n" +
        "        \"PitchingOnBasePlusSlugging\": 0.868,\n" +
        "        \"PitchingStrikeoutsPerNineInnings\": 8.22,\n" +
        "        \"PitchingWalksPerNineInnings\": 3.16,\n" +
        "        \"PitchingBattingAverageOnBallsInPlay\": 0.364,\n" +
        "        \"PitchingWeightedOnBasePercentage\": 0.396,\n" +
        "        \"DoublePlays\": 0.00,\n" +
        "        \"PitchingDoublePlays\": 8.00,\n" +
        "        \"BattingOrderConfirmed\": true,\n" +
        "        \"IsolatedPower\": 0,\n" +
        "        \"FieldingIndependentPitching\": 4.64,\n" +
        "        \"PitchingQualityStarts\": 6.00,\n" +
        "        \"PitchingInningStarted\": null,\n" +
        "        \"LeftOnBase\": 0.00,\n" +
        "        \"PitchingHolds\": 0.00,\n" +
        "        \"PitchingBlownSaves\": 0.00,\n" +
        "        \"SubstituteBattingOrder\": null,\n" +
        "        \"SubstituteBattingOrderSequence\": null,\n" +
        "        \"FantasyPointsFantasyDraft\": 191.55,\n" +
        "        \"FantasyPointsBatting\": 0.00,\n" +
        "        \"FantasyPointsPitching\": 50.66\n" +
        "    },\n" +
        "    {\n" +
        "        \"StatID\": 3605907,\n" +
        "        \"TeamID\": 1,\n" +
        "        \"PlayerID\": 10000014,\n" +
        "        \"SeasonType\": 1,\n" +
        "        \"Season\": 2022,\n" +
        "        \"Name\": \"Daniel Hudson\",\n" +
        "        \"Team\": \"LAD\",\n" +
        "        \"Position\": \"RP\",\n" +
        "        \"PositionCategory\": \"P\",\n" +
        "        \"Started\": 0,\n" +
        "        \"BattingOrder\": null,\n" +
        "        \"GlobalTeamID\": 10000001,\n" +
        "        \"AverageDraftPosition\": null,\n" +
        "        \"AuctionValue\": null,\n" +
        "        \"Updated\": \"2022-07-17T12:50:30\",\n" +
        "        \"Games\": 25,\n" +
        "        \"FantasyPoints\": 36.33,\n" +
        "        \"AtBats\": 0.00,\n" +
        "        \"Runs\": 0.00,\n" +
        "        \"Hits\": 0.00,\n" +
        "        \"Singles\": 0.00,\n" +
        "        \"Doubles\": 0.00,\n" +
        "        \"Triples\": 0.00,\n" +
        "        \"HomeRuns\": 0.00,\n" +
        "        \"RunsBattedIn\": 0.00,\n" +
        "        \"BattingAverage\": 0,\n" +
        "        \"Outs\": 0.00,\n" +
        "        \"Strikeouts\": 0.00,\n" +
        "        \"Walks\": 0.00,\n" +
        "        \"HitByPitch\": 0.00,\n" +
        "        \"Sacrifices\": 0.00,\n" +
        "        \"SacrificeFlies\": 0.00,\n" +
        "        \"GroundIntoDoublePlay\": 0.00,\n" +
        "        \"StolenBases\": 0.00,\n" +
        "        \"CaughtStealing\": 0.00,\n" +
        "        \"PitchesSeen\": 0.00,\n" +
        "        \"OnBasePercentage\": 0,\n" +
        "        \"SluggingPercentage\": 0,\n" +
        "        \"OnBasePlusSlugging\": 0,\n" +
        "        \"Errors\": 0.00,\n" +
        "        \"Wins\": 2.00,\n" +
        "        \"Losses\": 3.00,\n" +
        "        \"Saves\": 5.00,\n" +
        "        \"InningsPitchedDecimal\": 24.3333333333,\n" +
        "        \"TotalOutsPitched\": 73.00,\n" +
        "        \"InningsPitchedFull\": 24.00,\n" +
        "        \"InningsPitchedOuts\": 1.00,\n" +
        "        \"EarnedRunAverage\": 2.219,\n" +
        "        \"PitchingHits\": 17.00,\n" +
        "        \"PitchingRuns\": 7.00,\n" +
        "        \"PitchingEarnedRuns\": 6.00,\n" +
        "        \"PitchingWalks\": 5.00,\n" +
        "        \"PitchingStrikeouts\": 30.00,\n" +
        "        \"PitchingHomeRuns\": 1.00,\n" +
        "        \"PitchesThrown\": 406.00,\n" +
        "        \"PitchesThrownStrikes\": 256.00,\n" +
        "        \"WalksHitsPerInningsPitched\": 0.904,\n" +
        "        \"PitchingBattingAverageAgainst\": 0.191,\n" +
        "        \"GrandSlams\": 0.00,\n" +
        "        \"FantasyPointsFanDuel\": 157.00,\n" +
        "        \"FantasyPointsDraftKings\": 96.35,\n" +
        "        \"FantasyPointsYahoo\": 35.40,\n" +
        "        \"PlateAppearances\": 0.00,\n" +
        "        \"TotalBases\": 0.00,\n" +
        "        \"FlyOuts\": 0.00,\n" +
        "        \"GroundOuts\": 0.00,\n" +
        "        \"LineOuts\": 0.00,\n" +
        "        \"PopOuts\": 0.00,\n" +
        "        \"IntentionalWalks\": 0.00,\n" +
        "        \"ReachedOnError\": 0.00,\n" +
        "        \"BallsInPlay\": 0.00,\n" +
        "        \"BattingAverageOnBallsInPlay\": 0,\n" +
        "        \"WeightedOnBasePercentage\": 0,\n" +
        "        \"PitchingSingles\": 13.00,\n" +
        "        \"PitchingDoubles\": 3.00,\n" +
        "        \"PitchingTriples\": 0.00,\n" +
        "        \"PitchingGrandSlams\": 0.00,\n" +
        "        \"PitchingHitByPitch\": 2.00,\n" +
        "        \"PitchingSacrifices\": 0.00,\n" +
        "        \"PitchingSacrificeFlies\": 1.00,\n" +
        "        \"PitchingGroundIntoDoublePlay\": 1.00,\n" +
        "        \"PitchingCompleteGames\": 0.00,\n" +
        "        \"PitchingShutOuts\": 0.00,\n" +
        "        \"PitchingNoHitters\": 0.00,\n" +
        "        \"PitchingPerfectGames\": 0.00,\n" +
        "        \"PitchingPlateAppearances\": 97.00,\n" +
        "        \"PitchingTotalBases\": 23.00,\n" +
        "        \"PitchingFlyOuts\": 7.00,\n" +
        "        \"PitchingGroundOuts\": 19.00,\n" +
        "        \"PitchingLineOuts\": 5.00,\n" +
        "        \"PitchingPopOuts\": 2.00,\n" +
        "        \"PitchingIntentionalWalks\": 0.00,\n" +
        "        \"PitchingReachedOnError\": 2.00,\n" +
        "        \"PitchingCatchersInterference\": 0.00,\n" +
        "        \"PitchingBallsInPlay\": 59.00,\n" +
        "        \"PitchingOnBasePercentage\": 0.247,\n" +
        "        \"PitchingSluggingPercentage\": 0.258,\n" +
        "        \"PitchingOnBasePlusSlugging\": 0.505,\n" +
        "        \"PitchingStrikeoutsPerNineInnings\": 11.10,\n" +
        "        \"PitchingWalksPerNineInnings\": 1.85,\n" +
        "        \"PitchingBattingAverageOnBallsInPlay\": 0.271,\n" +
        "        \"PitchingWeightedOnBasePercentage\": 0.251,\n" +
        "        \"DoublePlays\": 0.00,\n" +
        "        \"PitchingDoublePlays\": 2.00,\n" +
        "        \"BattingOrderConfirmed\": true,\n" +
        "        \"IsolatedPower\": 0,\n" +
        "        \"FieldingIndependentPitching\": 2.04,\n" +
        "        \"PitchingQualityStarts\": 0.00,\n" +
        "        \"PitchingInningStarted\": null,\n" +
        "        \"LeftOnBase\": 0.00,\n" +
        "        \"PitchingHolds\": 9.00,\n" +
        "        \"PitchingBlownSaves\": 1.00,\n" +
        "        \"SubstituteBattingOrder\": null,\n" +
        "        \"SubstituteBattingOrderSequence\": null,\n" +
        "        \"FantasyPointsFantasyDraft\": 96.35,\n" +
        "        \"FantasyPointsBatting\": 0.00,\n" +
        "        \"FantasyPointsPitching\": 36.33\n" +
        "    },"